### ISSUE TITLE
בדיקת מטלה 7

### ISSUE THREAD

**Issue by michael-lemberger** [gamedev-srg/Speedtile-Dijkstra#1]
ביצעתי טסט פשוט נאיבי, אחד כזה שאפילו לא מצריך לפתוח את הפרוייקט ביוניטי.
כמובן מדובר על השאלה של דייאקסטרת מהירות, וראיתי שהאריח האפור מהיר יותר מהירוק הרגיל:
![image](https://user-images.githubusercontent.com/44966756/144216903-646ef5ef-ef56-4c73-aeb2-62fc25e501e0.png)
באדום אתם יכולים לראות את המסלול שהשחקן בוחר. אבל אני סימנתי בכחול מסלול אחד שברור שהוא יותר מהיר.
בקיצור, נראה שהאלגוריתם לא פועל נכון.

**Comment by gidon285** [comment]
היי מיכאל נכון, היה באג בגלל שלא שמנו לב שאראל השתמש במהירות כ 1\מהירות, לכן הערכים שונו. האלגוריתם נשאר זהה. תודה
